name: codifyiq_core_components
description: "Contains commonly used functional widgets.  CodifyIQ is open sourcing these for easy licensing and usage via standard pub mechanisms."
version: 0.3.0
homepage: https://github.com/CodifyIQ/codifyiq-core-components

flutter:
  uses-material-design: true

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gpt_markdown: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0